<?php

define('OOW_MAX_RELATIVE_ERROR', 1.5);

define('OOW_EARTH_AVERAGE_RADIUS', 6371);

/*
 * @link https://www.researchgate.net/publication/30871852_CONVERSION_OF_GPS_DATA_TO_CARTESIAN_COORDINATES_VIA_AN_APPLICATION_DEVELOPMENT_ADAPTED_TO_A_CAD_MODELLING_SYSTEM
 */

define('OOW_EARTH_MAJOR_RADIUS', 6378.137);

define('OOW_EARTH_MINOR_RADIUS', 6356.752);
